<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>приложение-задачник</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
        <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <script type="text/javascript" src="/js/jquery-2.2.4.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>    </head>
</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-default">
                    <div class="container-fluid">
                        <ul class="nav navbar-nav" >
                            
                            <?php

                                if ($_SERVER['REQUEST_URI'] == "/")
                                    echo "<li class='active'><a href='#'>Стартовая страница</a></li>";
                                else
                                    echo "<li><a href='/'>Стартовая страница</a></li>";

                                if ($_SERVER['REQUEST_URI'] == "/?action=addpost")
                                    echo "<li class='active'><a href='#'>Добавить задачу</a></li>";
                                else
                                    echo "<li><a href='/?action=addpost'>Добавить задачу</a></li>";                               
                                    
                                if (!isset($_SESSION['adminid']) OR !$_SESSION['adminid'])
                                {
                                    if ($_SERVER['REQUEST_URI'] == "/?action=login")
                                        echo "<li class='active'><a href='#'>Вход для Администратора</a></li>";
                                    else
                                        echo "<li><a href='/?action=login'>Вход для Администратора</a></li>";
                                }

                                if (isset($_SESSION['adminid']) AND $_SESSION['adminid']>0)
                                {
                                    echo "<li><a href='/?action=logout'>Выход</a></li>";
                                }

                            ?> 

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?= $this->content; ?>
            </div>
        </div>
        <hr>
        <footer>
            приложение-задачник / версия 1.0
        </footer>
    </div>
</body>
</html>
