<h1>Please login to add new post</h1>
<div class="row">

    <div class="col-md-8">

        Login <b>admin</b> and password <b>123</b>
        <?php
          if (isset($_REQUEST['error']) AND $_REQUEST['error']) 
            echo "<br /><q style='color:red'>Credentials are incorrect</q>";               
        ?>
        
        <form class="form-horizontal" action="/?action=loginsubmitted" method="post">
          <div class="form-group">
            <label class="control-label col-sm-2" for="email">Email:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="email" name="email" placeholder="Enter email">
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-2" for="password">Password:</label>
            <div class="col-sm-10"> 
              <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
            </div>
          </div>
          
          <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Submit</button>
            </div>
          </div>
        </form>

    </div>
</div>