<h1>Добавление задачи</h1>
<div class="row">

    <div class="col-md-8">

        <?php
        if (isset($_REQUEST['error']) AND $_REQUEST['error'])
            echo "<br /><q style='color:red'>Credentials are incorrect</q>";
        ?>

        <form action="/?action=addpostsubmitted" class="form-horizontal"  method="post">

          <div class="form-group">
            <label class="control-label col-sm-2" for="username">Пользователь:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="username" name="username" placeholder="Имя пользователя">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-sm-2" for="email">e-Mail:</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="email" name="email" placeholder="e-Mail">
            </div>
          </div>

          <div class="form-group">
            <label class="control-label col-sm-2" for="content">Текст задачи:</label>
            <div class="col-sm-10"> 
              <textarea class="form-control" id="content" name="content" width="120"></textarea>
            </div>
          </div>

          <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">Сохранить</button>
            </div>
          </div>

        </form>
        
    </div>
</div>
