<h1>Список задач</h1>
<div class="row">

    Порядок сортировки
    <ul id="">
        <li><a href='/?action=setorder&order=username'>Имя</a></li>
        <li><a href='/?action=setorder&order=email'>Email</a></li>
        <li><a href='/?action=setorder&order=status'>Статус</a></li>
    </ul>

    <div class="col-md-8">

    <?php

        $is_admin_mode = isset($_SESSION['adminid']) AND $_SESSION['adminid']>0;
        $escapeHtml = 'htmlspecialchars';
        $page = $GLOBALS["page"];
        $posts = array_chunk ( $variables, 3);
                 
        foreach ($posts[$page] as $postArray)
        {            
            $id = $postArray['id'];        
            $content = strip_tags($postArray['content']);
            if($is_admin_mode) $content = "<a href='/?action=post&id=$id'>".$content.'</a>';
    ?>
            <h4 align="right"><i><?= $escapeHtml($postArray['email']) ?></i></h4>
            <div class="content"><?= $content ?></div>
            <h4 align="right">
                Автор <b> <?= $escapeHtml($postArray['username']) ?></b>
                Опубликовано <b> <?= $escapeHtml(date('d/m/y',strtotime($postArray['date_created']))) ?> </b>
            </h4> 
            <?= $postArray['status']>0?"<i>отредактировано администратором</i>":"" ?>
            <hr />
    <?php
        }
    ?>
        <h3>
            <a href="/?page=<?= $page>0? $page-1:0 ?>"> <<<< </a>    
            страница <?= $page+1 ?>
            <a href="/?page=<?= (($page+1)<sizeof($posts))?$page+1:$page ?>"> >>>> </a>
        </h3>        
    </div>
</div>
