<div class="row">
    <div class="col-md-8">
      <?php
        $is_admin_mode = isset($_SESSION['adminid']) AND $_SESSION['adminid']>0;
        $escapeHtml = 'htmlspecialchars';
        $postArray = $variables;
        if ($postArray) 
        {
          $status = $postArray['status']?"checked":"";
        ?>
          <form action="/?action=addpostsubmitted" class="form-horizontal"  method="post">

            <input type = "hidden" readonly type="text" class="form-control" id="id" name="id" value="<?= strip_tags($postArray['id']) ?>">

            <div class="form-group">
              <label class="control-label col-sm-2" for="username">Пользователь:</label>
              <div class="col-sm-10">
                <input disabled type="text" class="form-control" id="username" name="username" 
                  value=<?= strip_tags($postArray['username']) ?>>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="email">e-Mail:</label>
              <div class="col-sm-10">
                <input disabled type="text" class="form-control" id="email" name="email" 
                  value=<?= strip_tags($postArray['email']) ?>>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="content">Текст задачи:</label>
              <div class="col-sm-10">
                <textarea class="form-control" rows="8" cols="45" id="content" name="content" width="120" >
                  <?= trim(strip_tags($postArray['content'])) ?>
                </textarea>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-sm-2" for="status">Выполнено:</label>
              <div class="col-sm-10">
                <input type="checkbox" <?= $status ?> class="form-control" id="status" name="status" >
              </div>
            </div>

            <div class="form-group"> 
              <div class="col-sm-offset-2 col-sm-10">
                <button <?= $is_admin_mode?"":"disabled" ?> type="submit" class="btn btn-default">Сохранить</button>
              </div>
            </div>

          </form>
            
      <?php
        }
      ?>
        <hr />
    </div>
</div>